name: helix

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-helix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test helix api
      run: npm run tsc && node ./tests/test.js