name: helix
env: 
  GITHUB_ACTIONS: true

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-helix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test helix api
      run: npm i && npm run tsc && node ./tests/test.js ${{ secrets.CLIENT_ID }} ${{ secrets.SECRET }}